### PR TITLE
use new instances of SimpleDateFormat instead of synchronized SimpleDateFormat object  

### PR DESCRIPTION
**Pull request by pussbb**
it's better to use new instances of SimpleDateFormat.
synchronized object of SimpleDateFormat does not give guarantee that date will be parsed correctly. New instances of SimpleDateFormat is more eficient for the multithread access.

### CODE REVIEW

**Comment by bshannon** [comment]
As the comment in the code says:
```
        /*
         * SimpleDateFormat objects aren't thread safe, so rather
         * than create a separate such object for each request,
         * we create one object and synchronize its use here
         * so that only one thread is using it at a time.  This
         * trades off some potential concurrency for speed in the
         * common case.
         *
         * This method is only used when formatting the date in a
         * message that's being appended to a folder.
         */
```
SimpleDateFormat is not being used to parse the date (MailDateFormat is used for that), it's being used to format the date.  If a lot of threads are appending messages to folders, I doubt that the
synchronization while formatting the dates is significant, but if you data that shows otherwise, I'd
love to see it.

**Comment by nvsnvikram** [comment]
This change would improve performance for us where we use imap client on server for supporting multiple users. We are appending messages on multiple users using different instances of the imap client.

**Comment by bshannon** [comment]
Do you have some performance data to show how much it would improve?
Compared to the cost of formatting the message and sending it to the server,
the cost of formatting the date should be insignificant.  I would expect it to
take very many users appending messages at exactly the same time to run
into contention with this lock.

**Comment by bshannon** [comment]
Lacking any performance data showing that this makes a significant difference,
I'm going to close this pull request.  Feel free to reopen it if you get such data.

**Pull request closed without merging**
