### PR TITLE
clean up connections when closing IMAPStore

### PR DESCRIPTION
**Pull request by pussbb**
IMAPStore.close  method must close all opened folders, release  protocols and set not connected for the current store

### CODE REVIEW

**Comment by bshannon** [comment]
Is there some reason you believe that IMAPStore.close does not currently do all those things?

It does seem like the close() logic has gotten unnecessarily complicated and your suggested
simplification might be worthwhile.  I'm still trying to think through all the possibilities to make
sure no important case will behave differently after the change.

It doesn't look like you've signed the [OCA](http://www.oracle.com/technetwork/community/oca-486395.html), can you please do so?

**Comment by pussbb** [comment]
as far as I understood doc string Service.close
```java
    /**
     * Close this service and terminate its connection. A close
     * ConnectionEvent is delivered to any ConnectionListeners. Any
     * Messaging components (Folders, Messages, etc.) belonging to this
     * service are invalid after this service is closed. Note that the service
     * is closed even if this method terminates abnormally by throwing
     * a MessagingException. <p>
     *
     * This implementation uses <code>setConnected(false)</code> to set
     * this service's connected state to <code>false</code>. It will then
     * send a close ConnectionEvent to any registered ConnectionListeners.
     * Subclasses overriding this method to do implementation specific
     * cleanup should call this method as a last step to insure event
     * notification, probably by including a call to <code>super.close()</code>
     * in a <code>finally</code> clause.
     *
     * @see javax.mail.event.ConnectionEvent
     * @throws	MessagingException	for errors while closing
     */
```

ImapStore.close must close all connections. but it seems that it does not.

> if (!super.isConnected()) // Already closed. 

condition will be true if ImapStore.cleanup method was invoked. 
ImapStore.close overides Service.close method but it does not invoke 
> super.close()


Method Service.close will be invoked only in ImapStore.cleanup method. 
and only after that registered ConnectionListeners will recive a close ConnectionEvent.

since 
> * Messaging components (Folders, Messages, etc.) belonging to this
> * service are invalid after this service is closed. Note that the service
> * is closed even if this method terminates abnormally by throwing
> * a MessagingException.

so ImapStore.close must close all authorized connections (close folders , connections).

from code
```java
	    synchronized (pool) {
 		// If there's no authenticated connections available
 		// don't create a new one
 		isEmpty = pool.authenticatedConnections.isEmpty();
 	    }
 	    /*
 	     * Have to drop the lock before calling cleanup.
 	     * Yes, there's a potential race here.  The pool could
 	     * become empty after we check, in which case we'll just
 	     * waste time getting a new connection and closing it.
 	     * Or, the pool could be empty now and not empty by the
 	     * time we get into cleanup, but that's ok because cleanup
 	     * will just close the connection.
 	     */
 	    if (isEmpty) {
 		pool.logger.fine("close() - no connections ");
 		cleanup();
 		return;
 	    }
```

folders and protocols(connections) will be closed only if pool is empty. If pool is not empty folders won't be closed ...


also 
> protocol = getStoreProtocol();

May create new authorized ImapProtocol if pool is empty and  I do not fully understand what for we need to create a new connection if we are tying 
to close any existing connections.

So I think that invoking ImapStore.cleanup method is right way to close ImapStore since this method closes all folders, than closes any connections in pool 
and calls super.close() method - which will mark Store as closed, and will send notification to registered ConnectionListeners. 

But I could be wrong. 

as for 
> It doesn't look like you've signed the OCA, can you please do so?
I will try to not forget to sign the OCA. but the project that uses javamail is currently suspended.

**Comment by bshannon** [comment]
Yes, this code is too complicated!  :-)

In the normal case, if cleanup is called from close because there are
no unused authenticated connections in the pool, the Folders will all
be closed in cleanup by the `if (!force || closeFoldersOnStoreFailure) {`
block (because force will not be set).

In the case where there is at least one unused authenticated connection
in the connection pool, the close method will get one of these
connections to use as the Store connection and will logout that Store
connection, which should cause a BYE response from the server, which
will cause the handleResponse method to set the connectionFailed flag,
which will cause the releaseStoreProtocol method called from the close
method to call cleanup, which will close all the Folders.

But cleanup also calls emptyConnectionPool, which will logout any
unused authenticated connections, so I'm not quite sure why the close
method needs to logout just one of these connections separately.
Calling cleanup directly from the close method would be much simpler.
This logout-in-close logic seems to be left over from when the Store
had a dedicated connection that was managed separately.

If another (non-close) Store operation fails to get a connection to the
server (e.g., because the server is dead), releaseStoreProtocol will
call cleanup with the forceClose flag set.  That will skip closing the
Folders (unless closeFoldersOnStoreFailure is set).

In that case, the Store will be closed but the Folders won't be closed,
so calling the close method will do nothing, and there will be no way
to force all the Folders to be closed.

Changing the close method to just call the cleanup method won't help
that, since the first thing the cleanup method does is check if the
Store is already closed and if so do nothing.

Refactoring the "close all Folders" loop so that it can be called from
cleanup in the closeFoldersOnStoreFailure case, or from close in
the normal case (without checking that the Store is already closed)
would probably fix that.

So, I'm thinking that close should be something like:

```
        closeAllFolders();
        cleanup();
```

I made this change and all my existing tests pass, but I need to write
some new test cases to verify the cases described above.

**Comment by bshannon** [comment]
I wrote some test cases and made further updates to the code based on test results.
If you can help test the changes, please contact me at javamail_ww@oracle.com.

**Comment by bshannon** [comment]
I wrote some test cases and made further updates to the code based on test results.
If you can help test the changes, please contact me at javamail_ww@oracle.com.

**Comment by bshannon** [comment]
@pussbb I never heard from you so I'm assuming you aren't able to test these changes.

I opened a bug #283 and pushed out my fixes to this problem.  I also pushed out a
1.6.1-SNAPSHOT release with these changes.

I'm closing this pull request, but let me know if you see any problems with my fixes.

**Pull request closed without merging**
