### PR TITLE
Add QUIT support on session rejection

### PR DESCRIPTION
**Pull request by diegosalvi**
Acutally on session initiation rejection (banner response 554 not 220) SMTPTransport abruptly closes the connection.

RFC5321 (https://tools.ietf.org/html/rfc5321#section-3.1) states that:
> The SMTP protocol allows a server to formally reject a mail session
> while still allowing the initial connection as follows: a 554
> response MAY be given in the initial connection opening message
> instead of the 220.  A server taking this approach MUST still wait
> for the client to send a QUIT (see Section 4.1.1.10) before closing
> the connection and SHOULD respond to any intervening commands with
> "503 bad sequence of commands".

The same RFC doesn't tell how client should react to session rejection so closing the connection is totally valid.

Pratically speaking I've encountered SMTP servers not behaving totally well to such conduct. To accomodate such servers I've added a new property `mail.smtp.quitonsessionreject` to send a QUIT command after session rejection, defaulting to false to keep old known behaviour.

### CODE REVIEW

**Comment by jmehrens** [comment]
You should use FINE instead of ALL for logging the debug/tracing messages.

**Comment by bshannon** [comment]
Thanks for the pull request.  Before I can accept it you need to sign the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) as described in the [Contribution Instructions](https://javaee.github.io/javamail/CONTRIBUTING).

Also, please file a corresponding issue and reference it in a change to the [CHANGES.txt](https://github.com/javaee/javamail/blob/master/doc/release/CHANGES.txt) file.

Also, a few typos in package.html:  "sent sent" -> "sent", "prior to close" -> "prior to closing"

**Comment by diegosalvi** [comment]
Fixed typos, log level and fille the changelog.

I will sign and submit the OCA tomorrow

**Comment by bshannon** [comment]
Have you submitted the OCA yet?  I don't see your name on the [list](http://www.oracle.com/technetwork/community/oca-486395.html#s).

In addition to resolving merge conflicts, at t his point you'll need to update the copyright year in the files you've touched.

If we can get the OCA resolved I'd like to merge this ASAP.

Thanks.

**Comment by bshannon** [comment]
It looks like you never submitted the OCA.  Since the JavaMail project is moving to the
Eclipse Foundation as part of the EE4J project, further updates will need to be done there.
You'll need to submit the Eclipse Contributor Agreement instead.

Unfortunately, I need to close this pull request.

**Pull request closed without merging**
