### PR TITLE
solve java.io.IOException: Unknown encoding problems for many emails

### PR DESCRIPTION
**Pull request by kwf2030**

### CODE REVIEW

**Comment by bshannon** [comment]
Unfortunately, as described [here](https://github.com/javaee/javamail/pull/311), this project is "in limbo"  while it's
in the process of being transferred to the Eclipse Foundation.  Sorry for that.

In the mean time, can you provide an example of a message that shows this problem?

**Comment by coltongit** [comment]
Any message, when sent through the API, may be affected by the bug described by @kwf2030, @bshannon , according to the nature of the affected code.

**Comment by bshannon** [comment]
Is there a real message that caused this problem?  Or did someone construct a message purposely to cause this problem?  If there's a real message, I'd like to see an example, because I've never seen this problem "in the wild".

**Comment by bshannon** [comment]
@godpit I understand how to force the error to occur.  What I'm looking for is a message
for which this error happens to occur.  Not an artificially constructed message, a real message
sent by a real mail program.

**Comment by godpit** [comment]
The mail was sent by phone app that its mail server program is jodd mail.

**Comment by bshannon** [comment]
I fixed this in a different way for JavaMail 1.6.2.

**Pull request closed without merging**
